version: '3'

services:
  db:
    image: postgres:latest
    container_name: kotikokki-database
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=kotikokki
     - POSTGRES_PASSWORD=kotikokki
     - POSTGRES_DB=kotikokki
  backend:
    image: kotikokki
    ports:
     - "80:80"
    depends_on:
     - db
    container_name: kotikokki
  metabase:
    image: metabase/metabase
    ports:
     - "3000:3000"
    depends_on:
     - db
     - backend
